/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmpManagement.Gui;

import EmpManagement.Dbutil.DBConnection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbtnAdd = new javax.swing.JRadioButton();
        rbtnSearch = new javax.swing.JRadioButton();
        rbtnDelete = new javax.swing.JRadioButton();
        rbtnDisplay = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        BtnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("Home");

        rbtnAdd.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(rbtnAdd);
        rbtnAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtnAdd.setForeground(new java.awt.Color(0, 102, 102));
        rbtnAdd.setText("Add Employees");

        rbtnSearch.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(rbtnSearch);
        rbtnSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtnSearch.setForeground(new java.awt.Color(0, 102, 102));
        rbtnSearch.setText("Search Employees");

        rbtnDelete.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(rbtnDelete);
        rbtnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtnDelete.setForeground(new java.awt.Color(0, 102, 102));
        rbtnDelete.setText("Delete Employees");

        rbtnDisplay.setBackground(new java.awt.Color(255, 204, 204));
        buttonGroup1.add(rbtnDisplay);
        rbtnDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rbtnDisplay.setForeground(new java.awt.Color(0, 102, 102));
        rbtnDisplay.setText("Display Employees");

        btnNext.setBackground(new java.awt.Color(0, 0, 0));
        btnNext.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 102));
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        BtnHome.setBackground(new java.awt.Color(0, 0, 0));
        BtnHome.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        BtnHome.setForeground(new java.awt.Color(255, 255, 102));
        BtnHome.setText("Home");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnDelete)
                            .addComponent(rbtnSearch)
                            .addComponent(rbtnDisplay)
                            .addComponent(rbtnAdd))))
                .addContainerGap(228, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnHome)
                .addGap(145, 145, 145))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(rbtnAdd)
                .addGap(18, 18, 18)
                .addComponent(rbtnSearch)
                .addGap(18, 18, 18)
                .addComponent(rbtnDelete)
                .addGap(18, 18, 18)
                .addComponent(rbtnDisplay)
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(BtnHome))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        boolean result=valiDateInput();
        if(!result){
            JOptionPane.showMessageDialog(null,"please select an operation");
            return;
        }
        JFrame frame=null;
        if(rbtnAdd.isSelected()){
            frame=new AddEmp();
        }
        else if(rbtnSearch.isSelected()) {
            frame=new SearchEmp();
        }
        else if(rbtnDisplay.isSelected()){
            frame=new ShowEmp();
        }
        else {
            DBConnection.closeConnection();
            System.exit(0);
        }
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    public boolean valiDateInput(){
        if(rbtnAdd.isSelected()==false &&rbtnSearch.isSelected()==false &&rbtnDelete.isSelected()==false&&rbtnDisplay.isSelected()==false)
            return false;
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHome;
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtnAdd;
    private javax.swing.JRadioButton rbtnDelete;
    private javax.swing.JRadioButton rbtnDisplay;
    private javax.swing.JRadioButton rbtnSearch;
    // End of variables declaration//GEN-END:variables
}
